### Adding, removing and sorting elements

In [1]:
import numpy as np

In [2]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [3]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [4]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [5]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [6]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [7]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [8]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([ 4,  1,  7, 14,  3, 14, 15,  6,  3, 16,  1,  8,  4,  0,  7,  1,  7,
       19,  5, 18], dtype=int32)

In [9]:
print(np.sort(integers_arr))

[ 0  1  1  1  3  3  4  4  5  6  7  7  7  8 14 14 15 16 18 19]


In [10]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [11]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [12]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [13]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


In [14]:
array_3d = np.random.randint(0, 10, size=(3, 4, 5))
array_3d

array([[[2, 6, 5, 8, 4],
        [6, 2, 0, 8, 2],
        [6, 4, 3, 9, 6],
        [8, 8, 0, 3, 1]],

       [[7, 3, 4, 6, 3],
        [5, 5, 1, 0, 5],
        [5, 9, 2, 5, 9],
        [5, 9, 9, 2, 4]],

       [[2, 2, 7, 6, 0],
        [9, 6, 6, 8, 8],
        [8, 3, 1, 9, 4],
        [6, 7, 3, 4, 8]]], dtype=int32)

In [15]:
sorted_3darray=np.sort(array_3d)
sorted_3darray

array([[[2, 4, 5, 6, 8],
        [0, 2, 2, 6, 8],
        [3, 4, 6, 6, 9],
        [0, 1, 3, 8, 8]],

       [[3, 3, 4, 6, 7],
        [0, 1, 5, 5, 5],
        [2, 5, 5, 9, 9],
        [2, 4, 5, 9, 9]],

       [[0, 2, 2, 6, 7],
        [6, 6, 8, 8, 9],
        [1, 3, 4, 8, 9],
        [3, 4, 6, 7, 8]]], dtype=int32)