### Copies and views

In [1]:
import numpy as np

In [2]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [3]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 140313891242320
id of students_ids_number_reg 140313891242320


In [4]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [5]:
students_ids_number_cp=students_ids_number.copy()

In [6]:
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [7]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [8]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 140313891242320
id of students_ids_number_cp 140313896668112


In [13]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [14]:
students_ids_number_v=students_ids_number.view()

In [15]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [17]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


In [1]:
import numpy as np

print("="*60)
print("UNDERSTANDING THE DIFFERENCE: .view() vs Direct Assignment")
print("="*60)

# Start fresh
original = np.array([1, 2, 3, 4, 5])

print("\n1. DIRECT ASSIGNMENT (students_ids_number_v = students_ids_number)")
print("-" * 60)

# Direct assignment - just another name for the SAME object
direct_ref = original
print(f"original:    {original}")
print(f"direct_ref:  {direct_ref}")
print(f"original id:    {id(original)}")
print(f"direct_ref id:  {id(direct_ref)}")
print(f"Are they the EXACT same object? {original is direct_ref}")  # True!

print("\n2. VIEW ASSIGNMENT (students_ids_number_v = students_ids_number.view())")
print("-" * 60)

# View - creates a NEW object that looks at the same data
view_ref = original.view()
print(f"original:   {original}")
print(f"view_ref:   {view_ref}")
print(f"original id:   {id(original)}")
print(f"view_ref id:   {id(view_ref)}")
print(f"Are they the EXACT same object? {original is view_ref}")  # False!
print(f"Do they share the same data? {np.shares_memory(original, view_ref)}")  # True!

print("\n" + "="*60)
print("ANALOGY: Think of it like a house")
print("="*60)
print("Direct assignment: Two people have keys to the SAME house")
print("View:             Two DIFFERENT houses built on the SAME foundation")

print("\n" + "="*60)
print("TEST 1: Modifying data through each reference")
print("="*60)

# Reset
original = np.array([1, 2, 3, 4, 5])
direct_ref = original
view_ref = original.view()

print("Before modification:")
print(f"original:   {original}")
print(f"direct_ref: {direct_ref}")
print(f"view_ref:   {view_ref}")

# Modify through direct reference
direct_ref[0] = 999
print(f"\nAfter direct_ref[0] = 999:")
print(f"original:   {original}")    # Changed!
print(f"direct_ref: {direct_ref}")  # Changed!
print(f"view_ref:   {view_ref}")    # Also changed!

# Modify through view
view_ref[1] = 888
print(f"\nAfter view_ref[1] = 888:")
print(f"original:   {original}")    # Changed!
print(f"direct_ref: {direct_ref}")  # Changed!
print(f"view_ref:   {view_ref}")    # Changed!

print("\n" + "="*60)
print("TEST 2: What happens when we reassign the original variable?")
print("="*60)

# Reset everything
original = np.array([10, 20, 30])
direct_ref = original           # Points to same object
view_ref = original.view()      # New object, shares data

print("Initial state:")
print(f"original:   {original}")
print(f"direct_ref: {direct_ref}")
print(f"view_ref:   {view_ref}")

# Now reassign 'original' to point to completely new data
old_data = original  # Keep reference to old data
original = np.array([100, 200, 300, 400])

print(f"\nAfter: original = np.array([100, 200, 300, 400])")
print(f"original:   {original}")      # New array
print(f"direct_ref: {direct_ref}")    # Still points to OLD array [10,20,30]
print(f"view_ref:   {view_ref}")      # Still points to OLD array [10,20,30]

print(f"\nAre direct_ref and view_ref still the same? {direct_ref is view_ref}")  # False
print(f"Do they still share memory? {np.shares_memory(direct_ref, view_ref)}")   # True

print("\n" + "="*60)
print("SUMMARY: When does the difference matter?")
print("="*60)
print("For most daily operations: NO difference")
print("- Both allow you to modify the underlying data")
print("- Both reflect changes made through the original")
print("")
print("The difference matters for:")
print("- Identity checks (using 'is')")
print("- Understanding object relationships in memory") 
print("- Debugging complex array operations")
print("- Understanding NumPy's memory management")

print("\n" + "="*60)
print("PRACTICAL RECOMMENDATION")
print("="*60)
print("Use .view() when you want to make it EXPLICIT that you're")
print("creating a new array object that shares data")
print("")
print("Use direct assignment when you just want another name")
print("for the same object (most common case)")

UNDERSTANDING THE DIFFERENCE: .view() vs Direct Assignment

1. DIRECT ASSIGNMENT (students_ids_number_v = students_ids_number)
------------------------------------------------------------
original:    [1 2 3 4 5]
direct_ref:  [1 2 3 4 5]
original id:    2372927211536
direct_ref id:  2372927211536
Are they the EXACT same object? True

2. VIEW ASSIGNMENT (students_ids_number_v = students_ids_number.view())
------------------------------------------------------------
original:   [1 2 3 4 5]
view_ref:   [1 2 3 4 5]
original id:   2372927211536
view_ref id:   2370857675984
Are they the EXACT same object? False
Do they share the same data? True

ANALOGY: Think of it like a house
Direct assignment: Two people have keys to the SAME house
View:             Two DIFFERENT houses built on the SAME foundation

TEST 1: Modifying data through each reference
Before modification:
original:   [1 2 3 4 5]
direct_ref: [1 2 3 4 5]
view_ref:   [1 2 3 4 5]

After direct_ref[0] = 999:
original:   [999   2   3