### Reshaping arrays

In [1]:
import numpy as np

In [2]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
fourth_arr=np.reshape(first_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [6]:
fifth_arr=np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is ",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


In [7]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [9]:
eighth_arr_flat=sixth_arr.flatten() # Creates a copy
print("eighth_arr_flat:",eighth_arr_flat)
ninth_arr_rav=sixth_arr.ravel() # Creates a view that references the original array
print("ninth_arr_rav:",ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [10]:
eighth_arr_flat[0]=100

In [11]:
ninth_arr_rav[0]=200

In [12]:
print("eighth_arr_flat:",eighth_arr_flat)
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

eighth_arr_flat: [100   2   3   4   5   6]
ninth_arr_rav: [200   2   3   4   5   6]
sixth_arr: [[200   2]
 [  3   4]
 [  5   6]]


In [21]:
long_array=np.arange(1,101)
long_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
fourthdimarray=np.reshape(long_array,(5,2,2,5))
fourthdimarray

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]]],


       [[[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]]],


       [[[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]]],


       [[[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [29]:
flat_array=np.reshape(fourthdimarray,(2,-1,5)) # -1 let numpy calculate the size of the other dimension
flat_array

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [30]:
flat_array.shape

(2, 10, 5)