### Array types and conversions between types

In [1]:
import numpy as np

In [2]:
integers=np.array([10,20,30,40,50])

In [3]:
integers

array([10, 20, 30, 40, 50])

In [4]:
integers[0]

np.int64(10)

In [5]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [6]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [7]:
integers.dtype

dtype('int64')

In [8]:
smallerIntegers=np.array(integers,dtype=np.int8)

In [9]:
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [10]:
integers.nbytes

40

In [11]:
smallerIntegers.nbytes

5

In [12]:
overflow = np.array([127,128,129], dtype = np.int8)
overflow

OverflowError: Python integer 128 out of bounds for int8

In [13]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])

In [14]:
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [15]:
floats.dtype

dtype('float64')