###  Finding the shape and size of an array

In [1]:
import numpy as np

In [2]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
second_arr=np.linspace((1,2,3),(10,20,30),10)
second_arr

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 3.,  6.,  9.],
       [ 4.,  8., 12.],
       [ 5., 10., 15.],
       [ 6., 12., 18.],
       [ 7., 14., 21.],
       [ 8., 16., 24.],
       [ 9., 18., 27.],
       [10., 20., 30.]])

In [4]:
second_arr2=np.linspace((1),(10,20,30),10) # Uses 1 as start for all 3 dimensions
second_arr2

array([[ 1.        ,  1.        ,  1.        ],
       [ 2.        ,  3.11111111,  4.22222222],
       [ 3.        ,  5.22222222,  7.44444444],
       [ 4.        ,  7.33333333, 10.66666667],
       [ 5.        ,  9.44444444, 13.88888889],
       [ 6.        , 11.55555556, 17.11111111],
       [ 7.        , 13.66666667, 20.33333333],
       [ 8.        , 15.77777778, 23.55555556],
       [ 9.        , 17.88888889, 26.77777778],
       [10.        , 20.        , 30.        ]])

In [5]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [6]:
np.shape(first_arr)

(20,)

In [7]:
np.shape(second_arr)

(10, 3)

In [8]:
np.shape(third_arr)

(2, 2, 2)

In [9]:
np.size(first_arr)

20

In [10]:
np.size(second_arr)

30

In [11]:
np.size(third_arr)

8